### ISSUE TITLE
Click in site tree opens in new window

### ISSUE THREAD

**Issue by DejanMilicic** [n2cms/n2cms#678]
In version 2.9, either clicking on an item in site tree to preview it, or opening for editing results in content not being loaded into the frameset, but new browser window opens.

**Comment by libardo** [comment]
This works on my machine. Any idea how I can reproduce this?

**Comment by DejanMilicic** [comment]
Happens in latest version of Chrome. I opened incognito window to eliminate any caching issues and managed to reproduce it there. Will try one more time after new version is pushed up.
Just to be cliear - left click on node in site tree, even click on menu item (like "edit") opens new tab in chrome and load content there.

**Comment by SntsDev** [comment]
I've seen some computers where this happens. But not in all of them, which is weird. I tried with Chrome 46 in Mac & PC with no problem, new window opens (not a tab). 

It is asked as a general issue in StackOverflow:
http://stackoverflow.com/questions/2572333/google-chrome-window-open-workaround?lq=1

**Comment by libardo** [comment]
I don't think the stackoverflow question is applicable in this case. Management uses 
`<a target="preview"... `
and
`<iframe name="preview"`
in both the tree and the top bar

**Comment by libardo** [comment]
@SntsDev Does this reproduce consistently in a specific browser? I've tried with or without the targeting module. Browsers: Chrome (46, 48), IE (Edge, 11,10,9 in emulator) and Firefox.

**Comment by Gidmark** [comment]
I think i get the same problem, but i get an error page as well in the details frame, and some 404s in the browser: (failwave.gif is part of the 404)
![capture](https://cloud.githubusercontent.com/assets/6553377/11101240/1f37c7fc-88b6-11e5-8dc6-5efdd4e46995.PNG)

The error:
Exception Details
Level 1
Type: System.Web.HttpUnhandledException
Source: System.Web
Target Site: Boolean HandleError(System.Exception)
Exception Information:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Level 2
Type: System.Web.HttpException
Source: System.Web
Target Site: Void FillNamedControlsTable(System.Web.UI.Control, System.Web.UI.ControlCollection)
Exception Information:
System.Web.HttpException (0x80004005): Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Message: Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
Stack Trace:
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by libardo** [comment]
I see all kinds of problems mentioned here.

![image](https://cloud.githubusercontent.com/assets/153667/11117884/c4de345c-893d-11e5-82fd-ed693bb934aa.png)

Am I correctly understanding that clicking on the marked links opens a new window rather than loading the link inside the preview frame?

**Comment by Gidmark** [comment]
Yes

Skickat från min iPhone

**Comment by Gidmark** [comment]
I don't get it on my dev machine but i get it on the production environment. Can it be something related to old crap being left behind?

**Comment by DejanMilicic** [comment]
I just experimentally upgraded on of my older projects and this problem does not occur anymore

**Comment by Gidmark** [comment]
Any idea what changed?

**Comment by SntsDev** [comment]
Hi there, I'm experiencing this same problem in my production machine. I don't know the eason, but what I can see is that the PREVIEW frame does not exist!!! How can it be not created or deleted? (v 2.9.3)

**Comment by SntsDev** [comment]
There is no big difference in the config, except for the conecctionString, Debug attribute and a Rewrite-Rule. Develpment: W7 (IIS7.5), Production: W12 (IIS8).

I found that in DEV it's not requiring the Targeting files, but in PROD it does. And, of course, if you don't install the N2CMS.Management.Targeting Package it won't find the files.

Before installing the package:
![captura-de-pantalla-2015-11-19-a-las-9 25 08](https://cloud.githubusercontent.com/assets/4103411/11266105/467322e8-8ea2-11e5-8660-1ae7544df0cb.png)

After installing the package: _no problem_.
```Install-Package N2CMS.Management.Targeting```

@libardo, How does N2 decide whether to use or not the Targeting functionality?

By the way, If in the ```system.web > customErrors``` of the web.config you add a 404 redirect rule the missing files will give a 302 instead of a 404. That might explain @Gidmark tracing.

**Comment by libardo** [comment]
By the presence of N2.Management.Targeting.dll in the bin folder

**Comment by libardo** [comment]
Any idea how it got there?

**Comment by SntsDev** [comment]
No idea

**Comment by SntsDev** [comment]
Isn't it included in the main packages? I didn't installed. I even didn't know it existed!

**Comment by libardo** [comment]
I checked all packages and it's only present in the targeting package. Any chance you could retrace your steps and re-do the upgrade in order to figure out where it came from? I think you can see a log of all changes in the output panel.

**Comment by SntsDev** [comment]
Yes, this was a 2.9.1 upgraded to 2.9.3. I cannot do that right now. But I'll come back to it.

**Comment by Gidmark** [comment]
It does have something to do with it for sure, i (re)moved the N2.Management.Targeting.dll and now it stopped opening in new windows... Is it safe to remove? :)

**Comment by libardo** [comment]
You can safely remove it. If you ever figure out how the dll was installed please let me know.
