### ISSUE TITLE
Error when logging in to admin

### ISSUE THREAD

**Issue by Gidmark** [n2cms/n2cms#679]
I get the following error when the UI is calling n2/Api/Context.ashx/full:

Server Error in '/' Application.
Value cannot be null.
Parameter name: virtualPath
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: virtualPath

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[ArgumentNullException: Value cannot be null.
Parameter name: virtualPath]
   System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options) +9895429
   N2.Edit.FileSystem.MappedFileSystem.MapPath(String virtualPath) in c:\Work\github\n2cms\src\Framework\N2\Edit\FileSystem\MappedFileSystem.cs:265
   N2.Edit.FileSystem.<GetDirectories>d__f.MoveNext() in c:\Work\github\n2cms\src\Framework\N2\Edit\FileSystem\MappedFileSystem.cs:52
   N2.Edit.FileSystem.Items.AbstractDirectory.GetDirectories() in C:\Work\github\n2cms\src\Mvc\MvcTemplates\N2\Files\FileSystem\Pages\AbstractDirectory.cs:75
   N2.Edit.FileSystem.Items.AbstractDirectory.GetChildren(ItemFilter filter) in C:\Work\github\n2cms\src\Mvc\MvcTemplates\N2\Files\FileSystem\Pages\AbstractDirectory.cs:99
   N2.Edit.FileSystem.Items.AbstractNode.N2.Definitions.IActiveChildren.GetChildren(ItemFilter filter) in C:\Work\github\n2cms\src\Mvc\MvcTemplates\N2\Files\FileSystem\Pages\AbstractNode.cs:107
   N2.Edit.NodeAdapter.GetNodeChildren(Query query) in c:\Work\github\n2cms\src\Framework\N2\Edit\NodeAdapter.cs:245
   N2.Edit.<GetChildren>d__11.MoveNext() in c:\Work\github\n2cms\src\Framework\N2\Edit\NodeAdapter.cs:220
   N2.Collections.BranchHierarchyBuilder.Build() in c:\Work\github\n2cms\src\Framework\N2\Collections\BranchHierarchyBuilder.cs:58
   N2.Management.Api.ApiExtensions.BuildBranchStructure(ItemFilter filter, IContentAdapterProvider adapters, ContentItem selectedItem, ContentItem root) in c:\Work\github\n2cms\src\Framework\N2\Edit\Api\ApiExtensions.cs:71
   N2.Management.Api.InterfaceBuilder.GetContent(HttpContextBase context, SelectionUtility selection, ContentItem selectedItem) in c:\Work\github\n2cms\src\Framework\N2\Edit\Api\InterfaceBuilder.cs:486
   N2.Management.Api.InterfaceBuilder.GetInterfaceDefinition(HttpContextBase context, SelectionUtility selection) in c:\Work\github\n2cms\src\Framework\N2\Edit\Api\InterfaceBuilder.cs:180
   N2.Management.Api.ContextHandler.ProcessRequest(HttpContextBase context) in c:\Work\github\n2cms\src\Framework\N2\Edit\Api\ContextHandler.cs:48
   N2.Management.Api.ApiHandlerDispatcher.ProcessRequest(HttpContext context) in c:\Work\github\n2cms\src\Framework\N2\Edit\Api\ApiHandlerDispatcher.cs:26
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.106.0 

I have the latest N2 2.9, and this makes the whole UI to just stay blank

**Comment by Gidmark** [comment]
Can this have anything to do with it?

ERROR 2015-11-10 18:31:40,326 11777ms ADOExceptionReporter   lambda_method      - The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK18406FA04B1A4E60". The conflict occurred in database "Customer_2015-10-04", table "dbo.n2Item", column 'VersionOfID'.
The statement has been terminated.
ERROR 2015-11-10 18:31:40,347 11798ms tFlushingEventListener lambda_method      - Could not synchronize database state with session
NHibernate.Exceptions.GenericADOException: could not execute batch command.[SQL: SQL not available] ---> System.Data.SqlClient.SqlException: The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK18406FA04B1A4E60". The conflict occurred in database "Customer_2015-10-04", table "dbo.n2Item", column 'VersionOfID'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientSqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)

**Comment by libardo** [comment]
@Gidmark I think your error is unrelated. It looks like a database constraint not removed by the upgrade. Do you have a FK relation ContentItem.VersionOf->ContentItem.ID in the database? It shouldn't be there.

**Comment by libardo** [comment]
The admin error is somehow related to uploads but I don't know how to reproduce it. Do you have some specific configuration related to uploads?

**Comment by Gidmark** [comment]
I even tried to rename the upload folder, still got the same error. But i don't think i have any special solutions going on. But i can try renaming it again and make sure i restart the iis express 

Best regards 
Mikael

**Comment by Gidmark** [comment]
Seems like it's something that comes and goes because now i get in. But i still get another error (unrelated i guess):

Path: /N2/Content/Edit.aspx

Exception Details
Level 1
Type: System.Web.HttpUnhandledException
Source: System.Web
Target Site: Boolean HandleError(System.Exception)
Exception Information:
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace:
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Level 2
Type: System.Web.HttpException
Source: System.Web
Target Site: Void FillNamedControlsTable(System.Web.UI.Control, System.Web.UI.ControlCollection)
Exception Information:
System.Web.HttpException (0x80004005): Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Message: Multiple controls with the same ID 'input' were found. FindControl requires that controls have unique IDs.
Stack Trace:
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
   at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
   at System.Web.UI.WebControls.BaseValidator.CheckControlValidationProperty(String name, String propertyName)
   at System.Web.UI.WebControls.BaseValidator.ControlPropertiesValid()
   at System.Web.UI.WebControls.BaseValidator.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by Gidmark** [comment]
Nope, it's back again, and renaming the Upload folder didn't help

**Comment by Gidmark** [comment]
When i debug i see that when this is called:

public virtual AbstractDirectory Directory
        {
            get 
            {
                if (Parent is AbstractDirectory)
                    return Parent as AbstractDirectory;
                else if (Parent is File)
                    return Parent.Parent as AbstractDirectory;
                else
                    return null;
            }
        }

Parent is nether a directory or a file, it seems to be the startpage, i wonder if that's the problem.

**Comment by Gidmark** [comment]
When i changed the parent page of the upload folder to be NULLthen it seems to work.. Maybe i've missed a todo when installing :)
