### ISSUE TITLE
Angular Script error in latest version

### ISSUE THREAD

**Issue by Hypnobrew** [n2cms/n2cms#727]
After updating to the latest N2 version 2.9.6.8 I'm getting a script error on Angular.

```
angular.js:4587 Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: Cannot set property 'aHrefSanitizationWhitelist' of null
    at $$SanitizeUriProvider (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:17679:35)
    at new <anonymous> (http://localhost:58587/Scripts/common.prototypes.js:16:12)
    at Object.instantiate (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:4680:14)
    at provider (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:4494:36)
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:366:32
    at forEach (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:336:20)
    at Object.provider (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:4484:9)
    at ngModule (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:2529:16)
    at Object.invoke (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:4665:19)
    at runInvokeQueue (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js:4558:35)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=ng&p1=TypeError%3A%…cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.5%2Fangular.js%3A4558%3A35)
```

It seems to be happened in the commit `5e5b1d162bf7557b137da756d2eb3afc3703cbd1` where the Angular version was updated.  
This is most likely related to the preview section because it does not render. If I set the previous version in the N2 host section like this everything works again, and the preview div renders: `<previewResources jQueryJsPath="~/Scripts/libs/jquery-1.11.3.min.js" angularJsRoot="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/" />`

**Comment by libardo** [comment]
Does this only happen in the preview frame?

/Scripts/common.prototypes.js seems to be involved somehow and isn't part of N2.

I would recommend checking the compatibilty of this component with angular 1.5.5. Using an older angular version probably works very well.

**Comment by Hypnobrew** [comment]
Hmm that's strange, there is nothing in there that should affect any native stuff in the javascript.
I'm a bit ashamed that I missed out the `Scripts/common.prototypes.js`.

Thanks!
